### ISSUE TITLE
[PowerNBT] PowerNBT v2.0-ALPHA-RC01 problems

### ISSUE THREAD

**Issue by mrcoffee1026** [flinbein/PowerNBT#36]
Basic commands no longer work:

/nbt Item.display view

"Not enough arguments"

Basically, any command comes back with "Not enough arguments", as a result no nbt can be viewed or modified.  All current documentation as for how commands work is no help whatsoever.  I have seen that it is possible - with a single command - to completely wipe out the entirety of my inventory and send myself to spawn, but this is never a desireable outcome.  Will be reverting to previous release version, will either need updated documentation or a fix for how commands used to function.

Thanks much!

**Comment by jb-aero** [comment]
This version sounds like it refers to a fork, so this particular issue should be reported to whoever you got that version from.

**Comment by mrcoffee1026** [comment]
No, it was this version but I failed to notice that development on this version ceased with 1.13, so of course nothing worked.

**Comment by DPOH-VAR** [comment]
`/nbt item display view`  
PowerNBT 1.+ works with craftbukkit api 1.17 and 1.18
